### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by steven-albanese**
Adding in the MIT license

### CODE REVIEW

**Comment by jchodera** [comment]
Is your plan to create a `SOFTWARE_LICENSE` file and a `DATA_USE_LICENSE` file, or just have `LICENSE` contain both license texts, specifying which belongs to which?

I think the two separate files might be useful.

**Comment by jchodera** [comment]
Along with a couple of lines of explanatory text in the `README.md`

**Comment by steven-albanese** [comment]
Two separate files sounds like a good idea. I'll switch to that

**Comment by jchodera** [comment]
We should include a full copy of the data license. You can grab a plaintext version [here](https://creativecommons.org/licenses/by/4.0/legalcode.txt).

**Comment by steven-albanese** [comment]
Thanks, I just added the full text version and updated the README

**Pull request merged**
